drop table if exists tcuenta;
drop table if exists tmovimientos;

drop sequence if exists tmovimientos_cmovimiento_seq;
create sequence tmovimientos_cmovimiento_seq;
alter sequence tmovimientos_cmovimiento_seq owner to root;

create table tcuenta
(
    cnumerocuenta integer not null
        primary key,
    ccliente      integer,
    estado        boolean,
    saldoinicial  numeric(38, 2),
    tipocuenta    varchar(255)
);
alter table tcuenta owner to root;

create table tmovimientos
(
    cmovimiento    integer generated by default as identity
        primary key,
    cnumerocuenta  integer,
    fecha          date,
    saldo          numeric(38, 2),
    tipomovimiento varchar(255),
    valor          numeric(38, 2)
);
alter table tmovimientos owner to root;
alter sequence tmovimientos_cmovimiento_seq owned by tmovimientos.cmovimiento;